services:
  mysql:
    image: mysql:8.0.38
    container_name: kuke-board-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - "3383:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - kuke-board-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4
    container_name: kuke-board-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - kuke-board-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:3.8.0
    container_name: kuke-board-kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kuke-board-network
    restart: unless-stopped

networks:
  kuke-board-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  kafka-data:
    driver: local